// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package models

import (
	"time"
)

type Choice struct {
	ID         int64
	QuestionID int64
	IsCorrect  bool
	Choice     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Question struct {
	ID        int64
	Question  string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserQuestionChoice struct {
	ID         int64
	UserID     int64
	ChoiceID   int64
	QuestionID int64
	IsCorrect  bool
	AnswerTime time.Time
}
