// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: queries.sql

package models

import (
	"context"
)

const createChoice = `-- name: CreateChoice :one
INSERT INTO choices (
    question_id, choice, is_correct
) VALUES (
             $1, $2, $3
         )
RETURNING id, question_id, is_correct, choice, created_at, updated_at
`

type CreateChoiceParams struct {
	QuestionID int64
	Choice     string
	IsCorrect  bool
}

func (q *Queries) CreateChoice(ctx context.Context, arg CreateChoiceParams) (Choice, error) {
	row := q.db.QueryRowContext(ctx, createChoice, arg.QuestionID, arg.Choice, arg.IsCorrect)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.IsCorrect,
		&i.Choice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    question
) VALUES (
             $1
         )
RETURNING id, question, is_active, created_at, updated_at
`

func (q *Queries) CreateQuestion(ctx context.Context, question string) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, question)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserQuestionChoice = `-- name: CreateUserQuestionChoice :one
INSERT INTO user_question_choice (
    user_id, choice_id, question_id, is_correct
) VALUES (
             $1, $2, $3, $4
         )
RETURNING id, user_id, choice_id, question_id, is_correct, answer_time
`

type CreateUserQuestionChoiceParams struct {
	UserID     int64
	ChoiceID   int64
	QuestionID int64
	IsCorrect  bool
}

func (q *Queries) CreateUserQuestionChoice(ctx context.Context, arg CreateUserQuestionChoiceParams) (UserQuestionChoice, error) {
	row := q.db.QueryRowContext(ctx, createUserQuestionChoice,
		arg.UserID,
		arg.ChoiceID,
		arg.QuestionID,
		arg.IsCorrect,
	)
	var i UserQuestionChoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChoiceID,
		&i.QuestionID,
		&i.IsCorrect,
		&i.AnswerTime,
	)
	return i, err
}

const getChoice = `-- name: GetChoice :one
SELECT id, question_id, is_correct, choice, created_at, updated_at FROM choices
WHERE question_id = $1 LIMIT 4
`

func (q *Queries) GetChoice(ctx context.Context, questionID int64) (Choice, error) {
	row := q.db.QueryRowContext(ctx, getChoice, questionID)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.IsCorrect,
		&i.Choice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, question, is_active, created_at, updated_at FROM questions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQuestion(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Question,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserQuestionChoice = `-- name: GetUserQuestionChoice :one
SELECT id, user_id, choice_id, question_id, is_correct, answer_time FROM user_question_choice
WHERE question_id = $1 LIMIT 1
`

func (q *Queries) GetUserQuestionChoice(ctx context.Context, questionID int64) (UserQuestionChoice, error) {
	row := q.db.QueryRowContext(ctx, getUserQuestionChoice, questionID)
	var i UserQuestionChoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChoiceID,
		&i.QuestionID,
		&i.IsCorrect,
		&i.AnswerTime,
	)
	return i, err
}

const listChoices = `-- name: ListChoices :many
SELECT id, question_id, is_correct, choice, created_at, updated_at FROM choices
ORDER BY id
`

func (q *Queries) ListChoices(ctx context.Context) ([]Choice, error) {
	rows, err := q.db.QueryContext(ctx, listChoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Choice
	for rows.Next() {
		var i Choice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.IsCorrect,
			&i.Choice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, question, is_active, created_at, updated_at FROM questions
ORDER BY id
`

func (q *Queries) ListQuestions(ctx context.Context) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Question,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
